# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc823ca4335563365b1d99fdc6689d7ac677b38d0252f552e13d3cd6a659bd92dbb9b0ba52d20110307fbae8a1ab82fdf939caca99c5605e47e336d0ce10d06a

test:
  secret_key_base: d29789afcd211d553ec4d42d26f2f250489fd371e19a831a7c83d681f4f5e42bea93257bed77e22fb9f08cf3ac27f0a85861de6ccd986240117a3c82d5b9afa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
